In [1]:
import pandas as pd
import numpy as np

employees_raw = pd.read_csv("employees.csv")
employees_raw.head()

,employee_id,first_name,last_name,role,region,branch_id,branch_name,hire_date,status,comp_plan_type,base_salary,target_bps,manager_id
0,100,Daniel,Carson,Loan Officer,Midwest,22,Chicago,2015-04-05,Active,bps,NaN,130.0,NaN
1,101,Daniel,Hernandez,Loan Officer,East,12,Charlotte,2021-07-02,Active,bps,NaN,80.0,NaN
2,102,Sophia,Shaw,Loan Officer,West,18,Los Angeles,2020-10-01,Active,bps,NaN,120.0,NaN
3,103,Rebecca,Hernandez,Loan Officer,South,30,Atlanta,2015-08-19,Active,bps,NaN,100.0,NaN
4,104,Emily,Turner,Loan Officer,South,30,Atlanta,2017-05-05,Active,bps,NaN,90.0,NaN

In [2]:
employees_raw.columns

Index(['employee_id', 'first_name', 'last_name', 'role', 'region', 'branch_id',
       'branch_name', 'hire_date', 'status', 'comp_plan_type', 'base_salary',
       'target_bps', 'manager_id'],
      dtype='object')

In [4]:
employees_raw.columns = (
    employees_raw.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("-", "_")
)

In [5]:
employees_raw.columns

Index(['employee_id', 'first_name', 'last_name', 'role', 'region', 'branch_id',
       'branch_name', 'hire_date', 'status', 'comp_plan_type', 'base_salary',
       'target_bps', 'manager_id'],
      dtype='object')

In [6]:
employees = employees_raw.rename(columns={
    "employee_id": "Employee ID",
    "first_name": "First Name",
    "last_name": "Last Name",
    "role": "Job Title",
    "region": "Region",
    "branch_id": "Branch ID",
    "branch_name": "Branch Location",
    "hire_date": "Hire Date",
    "status": "Employment Status",
    "comp_plan_type": "Compensation Type",
    "base_salary": "Salary",
    "target_bps": "BPS Compensation",
    "manager_id": "Manager ID"
})

In [7]:
employees_clean = employees.copy()
employees_clean.head()

,Employee ID,First Name,Last Name,Job Title,Region,Branch ID,Branch Location,Hire Date,Employment Status,Compensation Type,Salary,BPS Compensation,Manager ID
0,100,Daniel,Carson,Loan Officer,Midwest,22,Chicago,2015-04-05,Active,bps,NaN,130.0,NaN
1,101,Daniel,Hernandez,Loan Officer,East,12,Charlotte,2021-07-02,Active,bps,NaN,80.0,NaN
2,102,Sophia,Shaw,Loan Officer,West,18,Los Angeles,2020-10-01,Active,bps,NaN,120.0,NaN
3,103,Rebecca,Hernandez,Loan Officer,South,30,Atlanta,2015-08-19,Active,bps,NaN,100.0,NaN
4,104,Emily,Turner,Loan Officer,South,30,Atlanta,2017-05-05,Active,bps,NaN,90.0,NaN

In [8]:
employees_clean.info()
employees_clean.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75 entries, 0 to 74
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee ID        75 non-null     int64
 1   First Name         75 non-null     object
 2   Last Name          75 non-null     object
 3   Job Title          75 non-null     object
 4   Region             75 non-null     object
 5   Branch ID          75 non-null     int64
 6   Branch Location    75 non-null     object
 7   Hire Date          75 non-null     object
 8   Employment Status  75 non-null     object
 9   Compensation Type  75 non-null     object
 10  Salary             40 non-null     float64
 11  BPS Compensation   35 non-null     float64
 12  Manager ID         0 non-null      float64
dtypes: float64(3), int64(2), object(8)
memory usage: 7.7+ KB

,Employee ID,First Name,Last Name,Job Title,Region,Branch ID,Branch Location,Hire Date,Employment Status,Compensation Type,Salary,BPS Compensation,Manager ID
0,100,Daniel,Carson,Loan Officer,Midwest,22,Chicago,2015-04-05,Active,bps,NaN,130.0,NaN
1,101,Daniel,Hernandez,Loan Officer,East,12,Charlotte,2021-07-02,Active,bps,NaN,80.0,NaN
2,102,Sophia,Shaw,Loan Officer,West,18,Los Angeles,2020-10-01,Active,bps,NaN,120.0,NaN
3,103,Rebecca,Hernandez,Loan Officer,South,30,Atlanta,2015-08-19,Active,bps,NaN,100.0,NaN
4,104,Emily,Turner,Loan Officer,South,30,Atlanta,2017-05-05,Active,bps,NaN,90.0,NaN

In [9]:
# Convert Hire Date to datetime
employees_clean["Hire Date"] = pd.to_datetime(
    employees_clean["Hire Date"], errors="coerce"
)

# Convert numeric fields
employees_clean["Salary"] = pd.to_numeric(
    employees_clean["Salary"], errors="coerce"
)

employees_clean["BPS Compensation"] = pd.to_numeric(
    employees_clean["BPS Compensation"], errors="coerce"
)

employees_clean["Manager ID"] = pd.to_numeric(
    employees_clean["Manager ID"], errors="coerce"
)

In [10]:
employees_clean.loc[
    employees_clean["Compensation Type"] == "salary", "BPS Compensation"
] = 0

In [11]:
employees_clean.loc[
    employees_clean["Compensation Type"] == "bps", "Salary"
] = 0

In [15]:
employees_clean.head(5)

,Employee ID,First Name,Last Name,Job Title,Region,Branch ID,Branch Location,Hire Date,Employment Status,Compensation Type,Salary,BPS Compensation,Manager ID
0,100,Daniel,Carson,Loan Officer,Midwest,22,Chicago,2015-04-05,Active,bps,0.0,130.0,NaN
1,101,Daniel,Hernandez,Loan Officer,East,12,Charlotte,2021-07-02,Active,bps,0.0,80.0,NaN
2,102,Sophia,Shaw,Loan Officer,West,18,Los Angeles,2020-10-01,Active,bps,0.0,120.0,NaN
3,103,Rebecca,Hernandez,Loan Officer,South,30,Atlanta,2015-08-19,Active,bps,0.0,100.0,NaN
4,104,Emily,Turner,Loan Officer,South,30,Atlanta,2017-05-05,Active,bps,0.0,90.0,NaN

In [16]:
employees_clean["Tenure (Years)"] = (
    (pd.Timestamp("today") - employees_clean["Hire Date"]).dt.days / 365
).round(1)

In [17]:
employees_clean["Is BPS Compensation"] = (
    employees_clean["Compensation Type"] == "bps"
).astype(int)

In [18]:
employees_clean["Compensation Category"] = employees_clean["Compensation Type"].map({
    "bps": "BPS",
    "salary": "Salary"
})

In [19]:
employees_clean["Full Name"] = (
    employees_clean["First Name"] + " " + employees_clean["Last Name"]
)

In [20]:
employees_clean["Branch Label"] = (
    employees_clean["Branch Location"] + " - " + employees_clean["Branch ID"].astype(str)
)

In [21]:
employees_clean.head(10)

,Employee ID,First Name,Last Name,Job Title,Region,Branch ID,Branch Location,Hire Date,Employment Status,Compensation Type,Salary,BPS Compensation,Manager ID,Tenure (Years),Is BPS Compensation,Compensation Category,Full Name,Branch Label
0,100,Daniel,Carson,Loan Officer,Midwest,22,Chicago,2015-04-05,Active,bps,0.0,130.0,NaN,11.0,1,BPS,Daniel Carson,Chicago - 22
1,101,Daniel,Hernandez,Loan Officer,East,12,Charlotte,2021-07-02,Active,bps,0.0,80.0,NaN,4.8,1,BPS,Daniel Hernandez,Charlotte - 12
2,102,Sophia,Shaw,Loan Officer,West,18,Los Angeles,2020-10-01,Active,bps,0.0,120.0,NaN,5.5,1,BPS,Sophia Shaw,Los Angeles - 18
3,103,Rebecca,Hernandez,Loan Officer,South,30,Atlanta,2015-08-19,Active,bps,0.0,100.0,NaN,10.7,1,BPS,Rebecca Hernandez,Atlanta - 30
4,104,Emily,Turner,Loan Officer,South,30,Atlanta,2017-05-05,Active,bps,0.0,90.0,NaN,9.0,1,BPS,Emily Turner,Atlanta - 30
5,105,Noah,Nguyen,Loan Officer,East,12,Charlotte,2018-02-12,Active,bps,0.0,100.0,NaN,8.2,1,BPS,Noah Nguyen,Charlotte - 12
6,106,Harper,Johnson,Loan Officer,East,12,Charlotte,2019-09-04,Active,bps,0.0,110.0,NaN,6.6,1,BPS,Harper Johnson,Charlotte - 12
7,107,Sophia,Hernandez,Loan Officer,Midwest,22,Chicago,2022-10-28,Active,bps,0.0,100.0,NaN,3.5,1,BPS,Sophia Hernandez,Chicago - 22
8,108,Amelia,Shaw,Loan Officer,East,12,Charlotte,2012-11-08,Active,bps,0.0,100.0,NaN,13.4,1,BPS,Amelia Shaw,Charlotte - 12
9,109,Sophia,Price,Loan Officer,East,12,Charlotte,2018-05-15,Active,bps,0.0,130.0,NaN,7.9,1,BPS,Sophia Price,Charlotte - 12

In [22]:
employees_clean["Employee ID"].duplicated().sum()

0

In [23]:
employees_clean.duplicated().sum()

0

In [24]:
employees_clean.isna().sum()

Employee ID               0
First Name                0
Last Name                 0
Job Title                 0
Region                    0
Branch ID                 0
Branch Location           0
Hire Date                 0
Employment Status         0
Compensation Type         0
Salary                    0
BPS Compensation          0
Manager ID               75
Tenure (Years)            0
Is BPS Compensation       0
Compensation Category     0
Full Name                 0
Branch Label              0
dtype: int64

In [25]:
employees_clean["Job Title"].value_counts()

Job Title
Loan Officer           25
Underwriter            15
Processor              15
Account Executive      10
Branch Manager          5
Regional Manager        3
Operations Director     2
Name: count, dtype: int64

In [26]:
employees_clean["Compensation Type"].value_counts()

Compensation Type
salary    40
bps       35
Name: count, dtype: int64

In [27]:
employees_clean["Hire Date"].isna().sum()

0

In [28]:
employees_clean.info()
employees_clean.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75 entries, 0 to 74
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Employee ID            75 non-null     int64
 1   First Name             75 non-null     object
 2   Last Name              75 non-null     object
 3   Job Title              75 non-null     object
 4   Region                 75 non-null     object
 5   Branch ID              75 non-null     int64
 6   Branch Location        75 non-null     object
 7   Hire Date              75 non-null     datetime64[ns]
 8   Employment Status      75 non-null     object
 9   Compensation Type      75 non-null     object
 10  Salary                 75 non-null     float64
 11  BPS Compensation       75 non-null     float64
 12  Manager ID             0 non-null      float64
 13  Tenure (Years)         75 non-null     float64
 14  Is BPS Compensation    75 non-null     int32
 15  Compensation Category  75 non-null     object
 16  Full Name              75 non-null     object
 17  Branch Label           75 non-null     object
dtypes: datetime64[ns](1), float64(4), int32(1), int64(2), object(10)
memory usage: 10.4+ KB

,Employee ID,First Name,Last Name,Job Title,Region,Branch ID,Branch Location,Hire Date,Employment Status,Compensation Type,Salary,BPS Compensation,Manager ID,Tenure (Years),Is BPS Compensation,Compensation Category,Full Name,Branch Label
0,100,Daniel,Carson,Loan Officer,Midwest,22,Chicago,2015-04-05,Active,bps,0.0,130.0,NaN,11.0,1,BPS,Daniel Carson,Chicago - 22
1,101,Daniel,Hernandez,Loan Officer,East,12,Charlotte,2021-07-02,Active,bps,0.0,80.0,NaN,4.8,1,BPS,Daniel Hernandez,Charlotte - 12
2,102,Sophia,Shaw,Loan Officer,West,18,Los Angeles,2020-10-01,Active,bps,0.0,120.0,NaN,5.5,1,BPS,Sophia Shaw,Los Angeles - 18
3,103,Rebecca,Hernandez,Loan Officer,South,30,Atlanta,2015-08-19,Active,bps,0.0,100.0,NaN,10.7,1,BPS,Rebecca Hernandez,Atlanta - 30
4,104,Emily,Turner,Loan Officer,South,30,Atlanta,2017-05-05,Active,bps,0.0,90.0,NaN,9.0,1,BPS,Emily Turner,Atlanta - 30

In [29]:
employees_clean.to_csv("employees_clean.csv", index=False)