In [1]:
import pandas as pd
import numpy as np

loans_raw = pd.read_csv("loans.csv")
loans_raw.head()

,loan_number,application_date,lock_date,funding_date,loan_amount,property_state,property_type,occupancy_type,loan_purpose,channel,...,loan_status,loan_officer_id,account_executive_id,underwriter_id,processor_id,comp_bps,comp_amount,branch_id,pull_through_flag,num_extensions
0,70000001,2023-01-27,2023-01-30,NaN,439737,TX,SFR,Primary,Purchase,Wholesale,...,Canceled,123,156.0,127,150,90,3957.63,35,0,0
1,70000002,2023-03-26,2023-03-31,2023-05-15,621903,NY,SFR,Investment,Purchase,Retail,...,Funded,119,NaN,138,152,130,8084.74,35,1,0
2,70000003,2023-02-23,2023-02-28,NaN,580294,NY,Condo,Primary,Purchase,Retail,...,Denied,103,NaN,137,146,106,6151.12,30,0,0
3,70000004,2023-03-31,2023-04-04,2023-05-25,764044,CA,SFR,Investment,Purchase,Retail,...,Funded,119,NaN,130,152,128,9779.76,35,1,2
4,70000005,2023-03-20,2023-03-25,NaN,411397,VA,SFR,Investment,Purchase,Retail,...,Withdrawn,120,NaN,129,152,87,3579.15,35,0,0

In [4]:
loans_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 26 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   loan_number           10000 non-null  int64
 1   application_date      10000 non-null  object
 2   lock_date             10000 non-null  object
 3   funding_date          7014 non-null   object
 4   loan_amount           10000 non-null  int64
 5   property_state        10000 non-null  object
 6   property_type         10000 non-null  object
 7   occupancy_type        10000 non-null  object
 8   loan_purpose          10000 non-null  object
 9   channel               10000 non-null  object
 10  product_type          10000 non-null  object
 11  rate                  10000 non-null  float64
 12  fico_score            10000 non-null  int64
 13  cltv                  10000 non-null  int64
 14  dti                   10000 non-null  int64
 15  lock_term_days        10000 non-null  int64
 16  loan_status           10000 non-null  object
 17  loan_officer_id       10000 non-null  int64
 18  account_executive_id  4031 non-null   float64
 19  underwriter_id        10000 non-null  int64
 20  processor_id          10000 non-null  int64
 21  comp_bps              10000 non-null  int64
 22  comp_amount           10000 non-null  float64
 23  branch_id             10000 non-null  int64
 24  pull_through_flag     10000 non-null  int64
 25  num_extensions        10000 non-null  int64
dtypes: float64(3), int64(13), object(10)
memory usage: 2.0+ MB

In [5]:
loans_raw.columns

Index(['loan_number', 'application_date', 'lock_date', 'funding_date',
       'loan_amount', 'property_state', 'property_type', 'occupancy_type',
       'loan_purpose', 'channel', 'product_type', 'rate', 'fico_score', 'cltv',
       'dti', 'lock_term_days', 'loan_status', 'loan_officer_id',
       'account_executive_id', 'underwriter_id', 'processor_id', 'comp_bps',
       'comp_amount', 'branch_id', 'pull_through_flag', 'num_extensions'],
      dtype='object')

In [28]:
loans = loans_raw.rename(columns={
    "loan_number": "Loan Number",
    "application_date": "Application Date",
    "lock_date": "Lock Date",
    "funding_date": "Funding Date",
    "loan_amount": "Loan Amount",
    "property_type": "Property Type",
    "property_state": "Property State",
    "occupancy_type": "Occupancy Type",
    "loan_purpose": "Loan Purpose",
    "channel": "Channel",
    "product_type": "Product Type",
    "rate": "Interest Rate",
    "fico_score": "FICO",
    "cltv": "CLTV",
    "dti": "DTI",
    "lock_term_days": "Lock Term (days)",
    "loan_status": "Loan Status",
    "loan_officer_Id": "Loan Officer ID",
    "account_executive_id": "Account Executive ID",
    "underwriter_id": "Underwriter ID",
    "processor_id": "Processor ID",
    "comp_bps": "Compensation (BPS)",
    "comp_amount": "Compensation ($)",
    "branch_id": "Branch ID",
    "pull_through_flag": "Pull Through Flag",
    "num_extensions": "Extension Count"
})

In [29]:
loans_clean = loans.copy()

In [30]:
loans_clean.head(10)

,Loan Number,Application Date,Lock Date,Funding Date,Loan Amount,Property State,Property Type,Occupancy Type,Loan Purpose,Channel,...,Loan Status,loan_officer_id,Account Executive ID,Underwriter ID,Processor ID,Compensation (BPS),Compensation ($),Branch ID,Pull Through Flag,Extension Count
0,70000001,2023-01-27,2023-01-30,NaN,439737,TX,SFR,Primary,Purchase,Wholesale,...,Canceled,123,156.0,127,150,90,3957.63,35,0,0
1,70000002,2023-03-26,2023-03-31,2023-05-15,621903,NY,SFR,Investment,Purchase,Retail,...,Funded,119,NaN,138,152,130,8084.74,35,1,0
2,70000003,2023-02-23,2023-02-28,NaN,580294,NY,Condo,Primary,Purchase,Retail,...,Denied,103,NaN,137,146,106,6151.12,30,0,0
3,70000004,2023-03-31,2023-04-04,2023-05-25,764044,CA,SFR,Investment,Purchase,Retail,...,Funded,119,NaN,130,152,128,9779.76,35,1,2
4,70000005,2023-03-20,2023-03-25,NaN,411397,VA,SFR,Investment,Purchase,Retail,...,Withdrawn,120,NaN,129,152,87,3579.15,35,0,0
5,70000006,2023-03-04,2023-03-09,2023-04-17,389766,GA,SFR,Primary,Purchase,Retail,...,Funded,122,NaN,127,151,134,5222.86,18,1,0
6,70000007,2023-02-23,2023-02-26,2023-04-20,475907,FL,SFR,Primary,Refi RT,Retail,...,Funded,112,NaN,132,140,83,3950.03,22,1,2
7,70000008,2023-02-08,2023-02-11,2023-03-27,367275,TX,2-4 Unit,Primary,Refi RT,Retail,...,Funded,115,NaN,125,146,137,5031.67,18,1,0
8,70000009,2023-03-28,2023-03-31,2023-04-22,417491,IL,Condo,Investment,Refi CO,Retail,...,Funded,120,NaN,131,142,82,3423.43,35,1,2
9,70000010,2023-01-24,2023-01-24,2023-02-18,242711,GA,SFR,Primary,Purchase,Wholesale,...,Funded,115,163.0,125,151,130,3155.24,18,1,0

In [31]:
loans_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 26 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Loan Number           10000 non-null  int64
 1   Application Date      10000 non-null  object
 2   Lock Date             10000 non-null  object
 3   Funding Date          7014 non-null   object
 4   Loan Amount           10000 non-null  int64
 5   Property State        10000 non-null  object
 6   Property Type         10000 non-null  object
 7   Occupancy Type        10000 non-null  object
 8   Loan Purpose          10000 non-null  object
 9   Channel               10000 non-null  object
 10  Product Type          10000 non-null  object
 11  Interest Rate         10000 non-null  float64
 12  FICO                  10000 non-null  int64
 13  CLTV                  10000 non-null  int64
 14  DTI                   10000 non-null  int64
 15  Lock Term (days)      10000 non-null  int64
 16  Loan Status           10000 non-null  object
 17  loan_officer_id       10000 non-null  int64
 18  Account Executive ID  4031 non-null   float64
 19  Underwriter ID        10000 non-null  int64
 20  Processor ID          10000 non-null  int64
 21  Compensation (BPS)    10000 non-null  int64
 22  Compensation ($)      10000 non-null  float64
 23  Branch ID             10000 non-null  int64
 24  Pull Through Flag     10000 non-null  int64
 25  Extension Count       10000 non-null  int64
dtypes: float64(3), int64(13), object(10)
memory usage: 2.0+ MB

In [32]:
# Clean numeric columns by removing $, %, and commas
for col in numeric_cols:
    loans_clean[col] = (
        loans_clean[col]
        .astype(str)
        .str.replace(",", "", regex=False)
        .str.replace("$", "", regex=False)
        .str.replace("%", "", regex=False)
        .str.strip()
        .replace({"": None, "NA": None, "N/A": None, "None": None})
    )

In [33]:
for col in numeric_cols:
    loans_clean[col] = pd.to_numeric(loans_clean[col], errors="coerce")

In [34]:
# Define text columns
text_cols = [
    "Property State",
    "Occupancy Type",
    "Loan Purpose",
    "Channel",
    "Product Type",
    "Loan Status"
]

# Clean whitespace
for col in text_cols:
    loans_clean[col] = (
        loans_clean[col]
        .astype(str)
        .str.strip()
        .str.replace(r"\s+", " ", regex=True)
    )

# Standardize casing
for col in text_cols:
    loans_clean[col] = loans_clean[col].str.title()

In [35]:
loans_clean.head(10)

,Loan Number,Application Date,Lock Date,Funding Date,Loan Amount,Property State,Property Type,Occupancy Type,Loan Purpose,Channel,...,Loan Status,loan_officer_id,Account Executive ID,Underwriter ID,Processor ID,Compensation (BPS),Compensation ($),Branch ID,Pull Through Flag,Extension Count
0,70000001,2023-01-27,2023-01-30,NaN,439737,Tx,SFR,Primary,Purchase,Wholesale,...,Canceled,123,156.0,127,150,90,3957.63,35,0,0
1,70000002,2023-03-26,2023-03-31,2023-05-15,621903,Ny,SFR,Investment,Purchase,Retail,...,Funded,119,NaN,138,152,130,8084.74,35,1,0
2,70000003,2023-02-23,2023-02-28,NaN,580294,Ny,Condo,Primary,Purchase,Retail,...,Denied,103,NaN,137,146,106,6151.12,30,0,0
3,70000004,2023-03-31,2023-04-04,2023-05-25,764044,Ca,SFR,Investment,Purchase,Retail,...,Funded,119,NaN,130,152,128,9779.76,35,1,2
4,70000005,2023-03-20,2023-03-25,NaN,411397,Va,SFR,Investment,Purchase,Retail,...,Withdrawn,120,NaN,129,152,87,3579.15,35,0,0
5,70000006,2023-03-04,2023-03-09,2023-04-17,389766,Ga,SFR,Primary,Purchase,Retail,...,Funded,122,NaN,127,151,134,5222.86,18,1,0
6,70000007,2023-02-23,2023-02-26,2023-04-20,475907,Fl,SFR,Primary,Refi Rt,Retail,...,Funded,112,NaN,132,140,83,3950.03,22,1,2
7,70000008,2023-02-08,2023-02-11,2023-03-27,367275,Tx,2-4 Unit,Primary,Refi Rt,Retail,...,Funded,115,NaN,125,146,137,5031.67,18,1,0
8,70000009,2023-03-28,2023-03-31,2023-04-22,417491,Il,Condo,Investment,Refi Co,Retail,...,Funded,120,NaN,131,142,82,3423.43,35,1,2
9,70000010,2023-01-24,2023-01-24,2023-02-18,242711,Ga,SFR,Primary,Purchase,Wholesale,...,Funded,115,163.0,125,151,130,3155.24,18,1,0

In [36]:
loans_clean["Is Funded"] = (loans_clean["Loan Status"] == "Funded").astype(int)

In [37]:
loans_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 27 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Loan Number           10000 non-null  int64
 1   Application Date      10000 non-null  object
 2   Lock Date             10000 non-null  object
 3   Funding Date          7014 non-null   object
 4   Loan Amount           10000 non-null  int64
 5   Property State        10000 non-null  object
 6   Property Type         10000 non-null  object
 7   Occupancy Type        10000 non-null  object
 8   Loan Purpose          10000 non-null  object
 9   Channel               10000 non-null  object
 10  Product Type          10000 non-null  object
 11  Interest Rate         10000 non-null  float64
 12  FICO                  10000 non-null  int64
 13  CLTV                  10000 non-null  int64
 14  DTI                   10000 non-null  int64
 15  Lock Term (days)      10000 non-null  int64
 16  Loan Status           10000 non-null  object
 17  loan_officer_id       10000 non-null  int64
 18  Account Executive ID  4031 non-null   float64
 19  Underwriter ID        10000 non-null  int64
 20  Processor ID          10000 non-null  int64
 21  Compensation (BPS)    10000 non-null  int64
 22  Compensation ($)      10000 non-null  float64
 23  Branch ID             10000 non-null  int64
 24  Pull Through Flag     10000 non-null  int64
 25  Extension Count       10000 non-null  int64
 26  Is Funded             10000 non-null  int32
dtypes: float64(3), int32(1), int64(13), object(10)
memory usage: 2.0+ MB

In [38]:
date_cols = ["Application Date", "Lock Date", "Funding Date"]

for col in date_cols:
    loans_clean[col] = pd.to_datetime(loans_clean[col], errors="coerce")

In [39]:
loans_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 27 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Loan Number           10000 non-null  int64
 1   Application Date      10000 non-null  datetime64[ns]
 2   Lock Date             10000 non-null  datetime64[ns]
 3   Funding Date          7014 non-null   datetime64[ns]
 4   Loan Amount           10000 non-null  int64
 5   Property State        10000 non-null  object
 6   Property Type         10000 non-null  object
 7   Occupancy Type        10000 non-null  object
 8   Loan Purpose          10000 non-null  object
 9   Channel               10000 non-null  object
 10  Product Type          10000 non-null  object
 11  Interest Rate         10000 non-null  float64
 12  FICO                  10000 non-null  int64
 13  CLTV                  10000 non-null  int64
 14  DTI                   10000 non-null  int64
 15  Lock Term (days)      10000 non-null  int64
 16  Loan Status           10000 non-null  object
 17  loan_officer_id       10000 non-null  int64
 18  Account Executive ID  4031 non-null   float64
 19  Underwriter ID        10000 non-null  int64
 20  Processor ID          10000 non-null  int64
 21  Compensation (BPS)    10000 non-null  int64
 22  Compensation ($)      10000 non-null  float64
 23  Branch ID             10000 non-null  int64
 24  Pull Through Flag     10000 non-null  int64
 25  Extension Count       10000 non-null  int64
 26  Is Funded             10000 non-null  int32
dtypes: datetime64[ns](3), float64(3), int32(1), int64(13), object(7)
memory usage: 2.0+ MB

In [42]:
text_cols = [
    "Property State",
    "Property Type",
    "Occupancy Type",
    "Loan Purpose",
    "Channel",
    "Product Type",
    "Loan Status"
]

In [44]:
for col in text_cols:
    loans_clean[col] = (
        loans_clean[col]
        .astype(str)
        .str.strip()
        .str.replace(r"\s+", " ", regex=True)
    )

for col in text_cols:
    loans_clean[col] = loans_clean[col].str.title()

In [56]:
loans_clean["Total Time In Process"] = (
    loans_clean["App To Lock Days"].fillna(0) +
    loans_clean["Lock To Fund Days"].fillna(0)
)

In [57]:
loans_clean["App To Lock Days"] = (
    loans_clean["Lock Date"] - loans_clean["Application Date"]
).dt.days

In [58]:
loans_clean["Lock To Fund Days"] = (
    loans_clean["Funding Date"] - loans_clean["Lock Date"]
).dt.days

In [59]:
loans_clean["Days To Fund"] = (
    loans_clean["Funding Date"] - loans_clean["Application Date"]
).dt.days

In [60]:
bins = [0, 579, 619, 659, 699, 739, 799, 850]
labels = [
    "Poor (<580)",
    "Fair (580-619)",
    "Near Prime (620-659)",
    "Prime (660-699)",
    "Prime+ (700-739)",
    "Excellent (740-799)",
    "Elite (800+)"
]

loans_clean["FICO Bucket"] = pd.cut(loans_clean["FICO"], bins=bins, labels=labels)

In [61]:
bins = [0, 60, 70, 80, 90, 100, 200]
labels = [
    "<=60%",
    "61-70%",
    "71-80%",
    "81-90%",
    "91-100%",
    "100%+"
]

loans_clean["CLTV Bucket"] = pd.cut(loans_clean["CLTV"], bins=bins, labels=labels)

In [62]:
loans_clean["High DTI Flag"] = (loans_clean["DTI"] > 45).astype(int)

In [63]:
loans_clean.head()

,Loan Number,Application Date,Lock Date,Funding Date,Loan Amount,Property State,Property Type,Occupancy Type,Loan Purpose,Channel,...,Extension Count,Is Funded,Loan Age (Days),Days To Fund,App To Lock Days,Lock To Fund Days,FICO Bucket,CLTV Bucket,High DTI Flag,Total Time In Process
0,70000001,2023-01-27,2023-01-30,NaT,439737,Tx,Sfr,Primary,Purchase,Wholesale,...,0,0,1175,NaN,3,NaN,Excellent (740-799),91-100%,0,3.0
1,70000002,2023-03-26,2023-03-31,2023-05-15,621903,Ny,Sfr,Investment,Purchase,Retail,...,0,1,1117,50.0,5,45.0,Prime+ (700-739),81-90%,0,50.0
2,70000003,2023-02-23,2023-02-28,NaT,580294,Ny,Condo,Primary,Purchase,Retail,...,0,0,1148,NaN,5,NaN,Prime (660-699),71-80%,0,5.0
3,70000004,2023-03-31,2023-04-04,2023-05-25,764044,Ca,Sfr,Investment,Purchase,Retail,...,2,1,1112,55.0,4,51.0,Excellent (740-799),71-80%,0,55.0
4,70000005,2023-03-20,2023-03-25,NaT,411397,Va,Sfr,Investment,Purchase,Retail,...,0,0,1123,NaN,5,NaN,Excellent (740-799),71-80%,0,5.0

In [64]:
loans_clean["Loan Number"].duplicated().sum()

0

In [65]:
loans_clean.duplicated().sum()

0

In [66]:
loans_clean.isna().sum()

Loan Number                 0
Application Date            0
Lock Date                   0
Funding Date             2986
Loan Amount                 0
Property State              0
Property Type               0
Occupancy Type              0
Loan Purpose                0
Channel                     0
Product Type                0
Interest Rate               0
FICO                        0
CLTV                        0
DTI                         0
Lock Term (days)            0
Loan Status                 0
loan_officer_id             0
Account Executive ID     5969
Underwriter ID              0
Processor ID                0
Compensation (BPS)          0
Compensation ($)            0
Branch ID                   0
Pull Through Flag           0
Extension Count             0
Is Funded                   0
Loan Age (Days)             0
Days To Fund             2986
App To Lock Days            0
Lock To Fund Days        2986
FICO Bucket                 0
CLTV Bucket                 0
High DTI Flag               0
Total Time In Process       0
dtype: int64

In [67]:
loans_clean["Loan Status"].value_counts(dropna=False)

Loan Status
Funded       7014
Withdrawn    1034
Denied        787
Suspended     649
Canceled      516
Name: count, dtype: int64

In [68]:
loans_clean["Loan Status Simplified"] = loans_clean["Loan Status"].replace({
    "Canceled": "Withdrawn",
    "Denied": "Withdrawn",
    "Withdrawn": "Withdrawn"
})

In [70]:
loans_clean["Loan Status Simplified"].value_counts(dropna=False)

Loan Status Simplified
Funded       7014
Withdrawn    2337
Suspended     649
Name: count, dtype: int64

In [71]:
loans_clean["Product Type"].value_counts(dropna=False)

Product Type
Conventional    5527
Fha             1889
Jumbo           1690
Va               894
Name: count, dtype: int64

In [72]:
loans_clean["Channel"].value_counts(dropna=False)

Channel
Retail       5969
Wholesale    4031
Name: count, dtype: int64

In [73]:
loans_clean["Occupancy Type"].value_counts(dropna=False)

Occupancy Type
Primary        7507
Investment     1509
Second Home     984
Name: count, dtype: int64

In [74]:
loans_clean["Loan Purpose"].value_counts(dropna=False)

Loan Purpose
Purchase    5416
Refi Rt     3033
Refi Co     1551
Name: count, dtype: int64

In [75]:
loans_clean["Loan Purpose Simplified"] = loans_clean["Loan Purpose"].replace({
    "Purchase": "Purchase",
    "Refi Rt": "Refinance",
    "Refi Co": "Refinance"
})

In [76]:
loans_clean["Loan Purpose Simplified"].value_counts(dropna=False)

Loan Purpose Simplified
Purchase     5416
Refinance    4584
Name: count, dtype: int64

In [77]:
loans_clean.to_csv("loans_clean.csv", index=False)